name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install build tools
      run: ./install_build_tools.sh
    - name: Build nachos
      run: ./build_nachos.sh
    - name: Build coff2noff
      run: ./build_coff2noff.sh
    - name: Build and run tests
      run: ./build_test.sh
